version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        patterns:
          - "pytest*"
          - "ruff"
          - "mypy"
          - "build"
          - "twine"
      core-dependencies:
        patterns:
          - "pandas"
          - "plotly"
          - "pyyaml"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
